pipeline:
  release:
    image: appleboy/drone-ssh
    when:
      event: push
      branch:
        - master
    host:
      from_secret: deploy_host
    username:
      from_secret: deploy_user
    secrets: [ ssh_key ]
    port: 22
    script:
      - set -e
      - source ~/.bashrc
      - cd thui
      - git fetch
      - git reset HEAD --hard
      - git checkout ${DRONE_COMMIT_BRANCH}
      - git reset --hard origin/${DRONE_COMMIT_BRANCH}
      - docker-compose stop front
      - docker-compose up -d front

  telegram-PR:
    image: appleboy/drone-telegram
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_notification_chat_id
    format: markdown
    when:
      event: pull_request
    photo: ${DRONE_COMMIT_AUTHOR_AVATAR}
    message: >
      👉 Thui: New or update [PR](${DRONE_REPO_LINK}/pull/${DRONE_PULL_REQUEST}) from ${DRONE_COMMIT_AUTHOR}

  telegram-release:
    image: appleboy/drone-telegram
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_notification_chat_id
    format: html
    when:
      event: push
      branch:
        - master
      status:
        - success
        - failure
    message: >
      {{#success build.status}}
        🔔️ Thui: Release succeeded. Good job. Check <a href='http://thupoll.liinda.ru'>url</a>
      {{else}}
        ⛔ Thui: ALARM! Release failed. Check <a href='http://thupoll.liinda.ru'>url</a>
      {{/success}}
