version: "2"
services:
  front:
    image: node:8.12
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command: bash -c "cd /app/ && npm run deps && npm run client:build && cd server && node ."
